name: Docker Image CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: runner2
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/swagatam04/jboss-eap-api:latest
    
  publish-jboss-eap-runner-image:
    needs: build 
    runs-on: runner2
    steps:
    - uses: actions/checkout@v2
    - name: Build the hello-world Docker image
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin 
        docker push ghcr.io/swagatam04/jboss-eap-api:latest
 
