name: Docker Image CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: runner2
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
           mvn clean package wildfly:deploy
           docker build . --file Dockerfile --tag ghcr.io/swagatam04/jboss-eap-api:${{ github.sha }}
    
  

  publish-jboss-eap-runner-image:
     needs: build
     runs-on: runner2
     steps:
      - uses: actions/checkout@v2
      - name: Build the jboss-eap Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin 
          docker push ghcr.io/swagatam04/jboss-eap-api:${{ github.sha }}
          
  image-scan:
    needs: publish-jboss-eap-runner-image
    runs-on: deploy-server
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/swagatam04/jboss-eap-api:${{ github.sha }}'
          format: 'sarif'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'   
          
  run-jboss-eap-runner-image:
    needs: image-scan
    runs-on: deploy-server
    steps:
    - uses: actions/checkout@v2
    - name: Run Jboss-eap 
      run: |
        image=$(docker ps -a|grep jboss-eap-api|awk '{print $1}'|wc -l)
        echo $image
        if [ $image -ge 1 ];then 
          echo "Deleting existing image"
          docker rm -f $(docker ps -a|grep jboss-eap-api|awk '{print $1}')
        else
          echo "no image to delete"
        fi
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker run -itd -p 8008:8008 -p 9990:9990 ghcr.io/swagatam04/jboss-eap-api:${{ github.sha }}
        sleep 10

  check-application-health:
    needs: run-jboss-eap-runner-image
    runs-on: deploy-server
    steps:
    - uses: actions/checkout@v2
    - name: Run Application Health Check
      run: |
       curl -i -X POST http://18.191.209.230:8008/helloworld-html5/hello/json/swagatam -vk
 
