name: Docker Image CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: runner2
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/swagatam04/jboss-eap-api:latest
    
  publish-jboss-eap-runner-image:
    needs: build 
    runs-on: runner2
    steps:
    - uses: actions/checkout@v2
    - name: Build the jboss-eap Docker image
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin 
        docker push ghcr.io/swagatam04/jboss-eap-api:latest
  
  run-jboss-eap-runner-image:
    needs: publish-jboss-eap-runner-image 
    runs-on: deploy-server
    steps:
    - uses: actions/checkout@v2
    - name: Run Jboss-eap 
      run: |
        image=$(docker ps -a|grep jboss-eap-api|awk '{print $1}'|wc -l)
        echo $image
        if [ $image -ge 1 ];then 
          echo "Deleting existing image"
          docker rm -f $(docker ps -a|grep jboss-eap-api|awk '{print $1}')
        else
          echo "no image to delete"
        fi
        docker run -itd -p 8008:8008 -p 9990:9990 ghcr.io/swagatam04/jboss-eap-api:latest
        sleep 10

  check-application-health:
    needs: run-jboss-eap-runner-image
    runs-on: deploy-server
    steps:
    - uses: actions/checkout@v2
    - name: Run Application Health Check
      run: |
       curl -i -X POST http://18.191.209.230:8008/helloworld-html5/hello/json/swagatam -vk
 
  image-scan:
    needs: check-application-health
    runs-on: deploy-server
    steps:
      - name: Trivy Action
        # You may pin to the exact commit or the version.
        # uses: lazy-actions/gitrivy@6edf95fdc8b1fb841a974536316b209cd16f9000
        uses: lazy-actions/gitrivy@v3
        with:
          # Trivy version
          trivy_version: latest  # optional, default is latest
          # The target image name of vulnerability scan (specify this parameter or "IMAGE_NAME" environment variable
          image: ghcr.io/swagatam04/jboss-eap-api:latest  # optional
          # severities of vulnerabilities (separated by commma)
          #severity: HIGH,CRITICAL  # optional, default is HIGH,CRITICAL
          # target vlunerability [os,library] (separated by commma)
          vuln_type:  os,library # optional, default is os,library
          # Ignore unfixed vulnerabilities [true, false]
          ignore_unfixed: false # optional,false  default is false
          # GitHub access token used to create a issue
          token: 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
          
