# This is a basic workflow to help you get started with Actions
 
name:
  Cron Job for PR
 
  # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/2 * * * *"
 
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: runner2
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/swagatam04/jboss-eap-helloworld-restapi/merges \
            -d '{"base":"main","head":"feature","commit_message":"Shipped cool_feature!"}'
